# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
   - hugo
  except:
  - dev1

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - dev1

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add lftp
    - lftp -c "open $FTP_HOSTNAME; user $FTP_USERNAME $FTP_PASSWORD; mirror -Rev public/ web/appsdocs_V1.2_LD; quit"
