baseURL = '/'
languageCode = 'en-us'
title = 'AppsDocs Demo'
theme = "hugo-dsfr"

[params]
description =  "MINISTERE, <br>DE L'EDUCATION <BR> NATIONALE,<BR>ET DE LA JEUNESSE<BR>" 
subtitle = "Tutoriels et documentations pour les Apps.education.fr"
 
